//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ModuloPilotoSodexo.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ResponseReturnSAP
	{
		public virtual string TYPE
		{
			get;
			set;
		}

		public virtual string ID
		{
			get;
			set;
		}

		public virtual int NUMBER
		{
			get;
			set;
		}

		public virtual string MESSAGE
		{
			get;
			set;
		}

		public virtual string LOG_NO
		{
			get;
			set;
		}

		public virtual string LOG_MSG_NO
		{
			get;
			set;
		}

		public virtual string MESSAGE_V1
		{
			get;
			set;
		}

		public virtual string MESSAGE_V2
		{
			get;
			set;
		}

		public virtual string MESSAGE_V3
		{
			get;
			set;
		}

		public virtual string MESSAGE_V4
		{
			get;
			set;
		}

		public virtual string PARAMETER
		{
			get;
			set;
		}

		public virtual int ROW
		{
			get;
			set;
		}

		public virtual string FIELD
		{
			get;
			set;
		}

		public virtual string SYSTEM
		{
			get;
			set;
		}

	}
}

